import type { ModuleInfo } from "./types";

export const dasc506: ModuleInfo = {
  code: "DASC506",
  name: "DASC506",
  assessments: [
    {
      id: "dasc506-prediction-modelling",
      moduleCode: "DASC506",
      title: "Assignment 1 — Prediction Modelling",
      type: "Written report (individual), analysis performed in R (ideally using Rmarkdown), submitted as a single PDF via Canvas",
      weighting: "50%",
      wordCount: "1000 words + 10% (excluding all tables, references, code chunks, etc.)",
      submissionMethod:
        "The submission for this assignment should be one file in .pdf format submitted via Canvas. You can submit two files if one of them is your cover sheet and you are unable to attach it to your generated PDF file.",
      deadlineISO: "2027-04-12",
      deadlineDisplay: "Monday 12th April 2027, 4pm",
      deadlineConflictNote:
        "The student guide states only \"Submission Date: Monday 12th April at 4pm (via Canvas)\" with no year given anywhere in the document. The student has since confirmed the year is 2027, so that is used here.",
      learningOutcomes: [
        "Demonstrate the ability to develop and validate a clinical prediction model in R",
        "Demonstrate the ability to produce and describe output from understandable and useable R code",
        "Demonstrate the ability to communicate research and results suitably to the target audience",
      ],
      description:
        "The assignment is a written report on developing, validating and presenting a clinical prediction model using a dataset for mortality generated by artificial intelligence software (GAI). As this is a generated dataset, the focus of this assessment is on the justification of your choice of statistical methods. Do not worry about the clinical meaning of your prediction model, or how realistic it is if you have prior clinical experience. Also, if there are problems with your generated dataset (e.g. it leads to an empty prediction model), feel free to generate another dataset or to generate a larger dataset. You do not need to explain this as part of your write-up. Instead, summarise the dataset you have generated as required. For the sake of this assessment, assume that \"death\" relates to death in the first 14 days following a traumatic brain injury.",
      taskSteps: [
        {
          title: "Generate the dataset using generative AI",
          detail:
            'Use the following prompt or similar (modifying the file type to one of your choosing as required): "Generate an Excel file of 2500 patients, with a binary outcome for death, and four covariates: 1 continuous variable for age, 1 categorical variable for pupils reacting with possible answers both, one and none, 1 for hypertension with possible answers yes or no, and 1 for hypoxia with possible answers yes or no". Ensure you show the first few rows of the generated dataset as part of your submitted file.',
        },
        {
          title: "Summarise the characteristics of the generated dataset",
          detail:
            "Have a look at published journal articles to guide your choice of summary statistics as required.",
        },
        {
          title: "Develop a logistic regression prediction model",
          detail:
            "Develop a prediction model using logistic regression for the death outcome and determine which predictors should be included in the final model. Justify your choice of predictor selection method (e.g. backwards selection, forward selection, stepwise selection, no selection etc.). Ensure you interpret the model output.",
        },
        {
          title: "Evaluate model performance",
          detail:
            "Evaluate the performance of the model using all the appropriate measures described in lectures (DASC502 and DASC506 — remember to watch the recording of the DASC502 for a reminder/if this content is new to you).",
        },
        {
          title: "Internally validate the model",
          detail:
            "Internally validate the prediction model and adjust the model for any identified optimism (you will find the DASC502 practical useful for this — the resources are included in the assessments tab of DASC506 for convenience).",
        },
        {
          title: "Present the model for a clinical audience",
          detail:
            "Present the prediction model in a way that is suitable for a clinical audience (e.g. point score system, graphic score chart, nomogram, website/app etc.). You need only include one presentation method.",
        },
        {
          title: "Perform and write up the analysis in R",
          detail:
            "You are required to perform the analysis in R, ideally using Rmarkdown, and explain/justify all the code chunks. Justify the analysis methods you have chosen at each stage of the analysis. Please submit as a PDF.",
        },
      ],
      topBandGuidance:
        "Per the rubric's A* (80-100%) descriptors: characteristics of all predictors displayed and described to publication standard; successful fitting of a logistic regression with appropriate and fully justified consideration of predictors, full and appropriate interpretation and presentation of the full model, described to publication standard; evaluation of the full range of model performance statistics with appropriate interpretation and discussion; all relevant steps of internal validation described, justified and implemented to publication standard; appropriate and justified choice of presentation method with correct and full implementation and description, of publication standard; an Rmarkdown file organised logically with informative comments throughout, full code provided including library listings and code to generate tables, and comments detailing R and library versions; entirely logical flow with no spelling, punctuation or grammatical errors, only academic language, academically formatted and appropriately captioned tables and figures, and a large number of appropriate citations with references formatted to publication standard.",
      goodWorkLooksLike: [
        "Characteristics of all predictors appropriately displayed and described to publication standard",
        "A successfully fitted logistic regression model with fully justified consideration of predictors, and full, appropriate interpretation and presentation of the model",
        "Evaluation of the full range of model performance statistics, with appropriate interpretation and discussion",
        "All relevant internal validation steps described, justified and implemented (adjusting for optimism)",
        "An appropriately justified presentation method for a clinical audience, correctly and fully implemented and described",
        "An Rmarkdown file that is logically organised, clear to follow, with informative comments throughout (including R/library versions) and all code needed to complete the analysis",
        "Entirely logical flow, no spelling/punctuation/grammar errors, academic language throughout, appropriately captioned tables/figures, and a large number of appropriate citations and references",
      ],
      genAiTier:
        "Tier 4: Integrated (Integral / Embedded use). GenAI is required/core for generating the dataset only; once the dataset is generated, GenAI may be used only for \"contextual support (equivalent to Tier 2)\" — i.e. planning, editing, or support tasks, not producing main content or replacing the student's own thinking. All prompts used must be included on the cover sheet.",
      rubric: {
        status: "available",
        tables: [
          {
            criteria: [
              {
                name: "Summary of characteristics",
                weight: "5%",
                bands: [
                  {
                    band: "A* Distinction",
                    range: "80-100%",
                    text: "Characteristics of all predictors are appropriately displayed and described to publication standard. The summary could not be improved.",
                  },
                  {
                    band: "A Distinction",
                    range: "70-79%",
                    text: "Characteristics of all predictors are appropriately displayed and described to a high standard.",
                  },
                  {
                    band: "B Merit",
                    range: "60-69%",
                    text: "Characteristics of most predictors are appropriately displayed and described.",
                  },
                  {
                    band: "C Pass",
                    range: "50-59%",
                    text: "Characteristics of most predictors are displayed and described but not always appropriately.",
                  },
                  {
                    band: "D Fail",
                    range: "40-49%",
                    text: "Characteristics of some predictors are displayed but not described or vice versa.",
                  },
                  {
                    band: "F Fail",
                    range: "0-39%",
                    text: "Characteristics of predictors are not displayed or described.",
                  },
                ],
              },
              {
                name: "Development of a prediction model using logistic regression with consideration & interpretation of predictors to be included in the final model",
                weight: "20%",
                bands: [
                  {
                    band: "A* Distinction",
                    range: "80-100%",
                    text: "Successful fitting of a logistic regression with appropriate and fully justified consideration of predictors to be included in the final model. Full and appropriate interpretation and presentation of the full model. Model fitting described to publication standard.",
                  },
                  {
                    band: "A Distinction",
                    range: "70-79%",
                    text: "Successful fitting of a logistic regression model with appropriate and justified consideration of predictors to be included in the final model. Complete interpretation and presentation full model.",
                  },
                  {
                    band: "B Merit",
                    range: "60-69%",
                    text: "Fitting of a logistic regression model with appropriate and fairly justified consideration of predictors to be included in the final model. Interpretation and presentation of most aspects of the full model.",
                  },
                  {
                    band: "C Pass",
                    range: "50-59%",
                    text: "Fitting of a logistic regression model with an attempt to justify predictors to be included in the final model. Interpretation and presentation of some aspects of the full model.",
                  },
                  {
                    band: "D Fail",
                    range: "40-49%",
                    text: "Logistic regresison [sic] model fitted but no attempt to justify predictors to be included in the final model. Presentation of at least one aspect of the full model.",
                  },
                  {
                    band: "F Fail",
                    range: "0-39%",
                    text: "No logistic regression model fitted.",
                  },
                ],
                sourceNote:
                  "Rubric text contains the verbatim typo \"Logistic regresison\" in the D band; reproduced as-is.",
              },
              {
                name: "Evaluation of model performance",
                weight: "20%",
                bands: [
                  {
                    band: "A* Distinction",
                    range: "80-100%",
                    text: "Evaluation of full range of model performance statistics with appropriate interpretation and discussion.",
                  },
                  {
                    band: "A Distinction",
                    range: "70-79%",
                    text: "Evaluation of full range of model performance statistics with mostly appropriate interpretation and discussion.",
                  },
                  {
                    band: "B Merit",
                    range: "60-69%",
                    text: "Evaluation of a wide range of model performance statistics with some appropriate interpretation and discussion.",
                  },
                  {
                    band: "C Pass",
                    range: "50-59%",
                    text: "Evaluation of a range of model performance statistics with some interpretation and discussion, but it may not be appropriate.",
                  },
                  {
                    band: "D Fail",
                    range: "40-49%",
                    text: "Evaluation of at least one model performance statistic with some interpretation and discussion, but it may not be appropriate.",
                  },
                  {
                    band: "F Fail",
                    range: "0-39%",
                    text: "No model performance evaluation.",
                  },
                ],
              },
              {
                name: "Internal validation of the model",
                weight: "15%",
                bands: [
                  {
                    band: "A* Distinction",
                    range: "80-100%",
                    text: "All relevant steps associated with internal validation have been described, justified and implemented. The description is of publication standard.",
                  },
                  {
                    band: "A Distinction",
                    range: "70-79%",
                    text: "All relevant steps associated with internal validation have been described, justified and implemented.",
                  },
                  {
                    band: "B Merit",
                    range: "60-69%",
                    text: "Most relevant steps associated with internal validation have been described, justified and implemented.",
                  },
                  {
                    band: "C Pass",
                    range: "50-59%",
                    text: "Most relevant steps associated with internal validation have been described, with limited justified [sic].",
                  },
                  {
                    band: "D Fail",
                    range: "40-49%",
                    text: "Some relevant steps associated with internal validation have been described, without justification.",
                  },
                  {
                    band: "F Fail",
                    range: "0-39%",
                    text: "No internal validation.",
                  },
                ],
                sourceNote:
                  "C band contains the verbatim phrase \"with limited justified\" (likely intended \"justification\"); reproduced as-is.",
              },
              {
                name: "Presentation of the model for a clinical audience",
                weight: "25%",
                bands: [
                  {
                    band: "A* Distinction",
                    range: "80-100%",
                    text: "Appropriate and justified choice of presentation method, with correct and full implementation and description of the resulting item. Of publication standard.",
                  },
                  {
                    band: "A Distinction",
                    range: "70-79%",
                    text: "Appropriate and justified choice of presentation method, with correct and full implementation and description of the resulting item.",
                  },
                  {
                    band: "B Merit",
                    range: "60-69%",
                    text: "Appropriate and mostly justified choice of presentation method, with mostly correct implementation and description of the resulting item.",
                  },
                  {
                    band: "C Pass",
                    range: "50-59%",
                    text: "Presentation method chosen and implemented to some degree, but without justification.",
                  },
                  {
                    band: "D Fail",
                    range: "40-49%",
                    text: "Presentation method chosen without justificaiton [sic] and without successful implementation.",
                  },
                  {
                    band: "F Fail",
                    range: "0-39%",
                    text: "No presentation method.",
                  },
                ],
                sourceNote:
                  "D band contains the verbatim typo \"justificaiton\"; reproduced as-is.",
              },
              {
                name: "R code clarity and justification",
                weight: "10%",
                bands: [
                  {
                    band: "A* Distinction",
                    range: "80-100%",
                    text: "R markdown file has been submitted. It is organised logically, and it is clear and easy for the reader to follow what has been done. There are informative comments throughout, and the code needed to complete the analysis is fully provided (e.g. listing of libraries used, code to generate tables etc.). Comments contain details of versions of R and libraries used",
                  },
                  {
                    band: "A Distinction",
                    range: "70-79%",
                    text: "R markdown file has been submitted. It is organised logically, and it is clear for the reader to follow what has been done. There are comments throughout, and the code needed to complete the analysis is provided (e.g. listing of libraries used, code to generate tables etc.)",
                  },
                  {
                    band: "B Merit",
                    range: "60-69%",
                    text: "R markdown file has been submitted. It is organised in a logical manner, and it is relatively easy for the reader to follow what has been done. There are some comments, and most of the code needed to complete the analysis is provided (e.g. listing of libraries used, code to generate tables etc.)",
                  },
                  {
                    band: "C Pass",
                    range: "50-59%",
                    text: "R script or R markdown file has been submitted. It is not well organised, and it is difficult to follow what has been done easily. Comments are minimal and/or uninformative. Sections of code might be missing/incomplete (e.g. listing of libraries used, code to generate tables etc.)",
                  },
                  {
                    band: "D Fail",
                    range: "40-49%",
                    text: "A minimal R file has been submitted. It is disorganised, uncommented and incomplete (missing key sections of code)",
                  },
                  {
                    band: "F Fail",
                    range: "0-39%",
                    text: "No R file has been submitted",
                  },
                ],
              },
              {
                name: "Overall structure and presentation",
                weight: "5%",
                bands: [
                  {
                    band: "A* Distinction",
                    range: "80-100%",
                    text: "Entirely logical flow with no spelling, punctuation or grammatic errors and use of only academic language throughout. This could not be improved. Tables use the academic format and are appropriately captioned. Figures are appropriately labelled and captioned. There are a large number of appropriate citations with associated references and the formatting is of publication standard.",
                  },
                  {
                    band: "A Distinction",
                    range: "70-79%",
                    text: "Entirely logical flow with no spelling, punctuation or grammatic errors and use of only academic language throughout. The tables are appropriately captioned. Figures are appropriately labelled and captioned. There are a large number of appropriate citations with associated references.",
                  },
                  {
                    band: "B Merit",
                    range: "60-69%",
                    text: "Mostly logical flow with rare spelling, punctuation or grammatical errors and only minor deviations from academic language. The tables are appropriately captioned. Figures are appropriately labelled and captioned. There are a appropriate [sic] citations with associated references.",
                  },
                  {
                    band: "C Pass",
                    range: "50-59%",
                    text: "Fairly logical flow with some spelling, punctuation or grammatical errors and several deviations from academic language. The tables are inadequately captioned. Figures are inadequately labelled and captioned. There are limited citations with or without associated references and there are errors with the formatting.",
                  },
                  {
                    band: "D Fail",
                    range: "40-49%",
                    text: "Generally illogical flow with many spelling, punctuation or grammatical errors and multiple deviations from academic language. Tables are not captioned. Figures are not labelled and captioned. There are no citations and/or no references.",
                  },
                  {
                    band: "F Fail",
                    range: "0-39%",
                    text: "No submission",
                  },
                ],
                sourceNote:
                  "B band contains the verbatim phrase \"a appropriate\" (grammatical typo in source); reproduced as-is.",
              },
            ],
            academicIntegrity: [
              {
                label: "No concerns",
                text: "There are no academic integrity concerns with this assignment",
              },
              {
                label: "Category 1",
                text: "Poor Academic Practice. The assessed mark is capped at minimum pass grade (50%). Assessors are advised to consult with the Academic Integrity Officer (mesudell@liverpool.ac.uk)",
              },
              {
                label: "Category 2, 3, 4",
                text: "(Plagiarism, Copying, Collusion, Submission of Unacceptable Artificial Intelligence Generated Assessment Tasks, Embellishment or Falsification of Data, Purchased or commissioned work). All suspected Cat 2, 3, 4 cases must be referred to the Academic Integrity Officer (mesudell@liverpool.ac.uk)",
              },
            ],
          },
        ],
      },
      readingRefs: [
        {
          title: "Best Practices for Writing R Code",
          note: "https://swcarpentry.github.io/r-novice-inflammation/06-best-practices-R.html",
        },
        {
          title: "The tidyverse style guide",
          note: "https://style.tidyverse.org/",
        },
        {
          title: "Examples of scientific writing",
          note: "Available on the general Health Data Science PGT Canvas page",
        },
        {
          title: "RMarkdown (introduced in DASC503 week 8 data lab)",
        },
        {
          title: "An introductory guide to RMarkdown",
          note: "https://rmarkdown.rstudio.com/articles_intro.html",
        },
      ],
      gaps: [
        "The Assignment 1 guide gives no year for its submission date (\"Monday 12th April at 4pm\") — the student has confirmed the year as 2027, used above.",
        "No explicit page limit or time limit is stated (only a word limit).",
        "Weighting of 50% is not stated directly in the Assignment 1 guide or rubric itself; it is inferred from the module-level statement in the Assignment 2 guide's introduction that the two DASC506 assignments are \"each worth 50%\".",
      ],
    },
    {
      id: "dasc506-joint-modelling",
      moduleCode: "DASC506",
      title: "Assignment 2 — Joint Modelling",
      type: "Written report (individual), formatted as the methods and results section of a short journal article aimed at a clinical audience, analysis conducted in R, submitted as a single PDF via Canvas",
      weighting: "50%",
      wordCount: "2500 words (+ 10%, excluding all tables, references, code chunks, etc.)",
      submissionMethod:
        "The submission for this assignment should be one file in .pdf format submitted via canvas",
      deadlineISO: "2027-05-18",
      deadlineDisplay: "Tuesday 18th May 2027 by 1600",
      setDate: "Week 1, Semester 2",
      learningOutcomes: [
        "Demonstrate the ability to plan and carry out complex statistical analyses using advanced statistical methods and dedicated statistical software in R.",
        "Describe the suitability of planned analysis methods to answer the posed research question.",
        "Describe planned methods with enough detail for a skilled researcher to replicate the analysis exactly",
        "Present appropriate visualizations of data and model estimates.",
        "Interpret and communicate the findings effectively in written formats for clinical audiences.",
      ],
      description:
        "There are two assignments in DASC506, each worth 50%. The first (Assignment 1) relates to the time-to-event and the prediction modelling content. The second (Assignment 2) involves the longitudinal, time-to-event, and joint modelling content. This is Assignment 2. Students will plan and perform an analysis in R of a dataset containing both longitudinal and time-to-event information. Students will write up the analysis and results in the format of the methods and results section of a short journal article aimed at a clinical audience. An abstract, an introduction, and a discussion section are not required. There is a hard limit of 5 tables and 5 figures for this assignment — this is a limit, not a target. Panelling multiple graphs within a single figure is acceptable if readable.",
      taskSteps: [
        {
          title: "Download and load the dataset",
          detail:
            "Download aidsdat.dat from Canvas. \"Assignment - help loading the dataset.R\" provides the R coding file explaining how to load the dataset in .dat format into R (available on Canvas). This dataset is a sample of 450 individuals from the aids data available from the joineR package. Details of the variables can be obtained by loading the joineR library in R and using the command ?aids. Note: as this is a bootstrapped sample of the dataset available in joineR, results will differ slightly from example analyses in joineR, or papers published on the original aids dataset.",
        },
        {
          title: "Identify outcomes and covariates",
          detail:
            "Longitudinal outcome: CD4 — the CD4 cell count measured at obstime. Time-to-event outcome: death (censoring variable), time (time to death or censoring). Always include the covariate drug (drug indicator) in the longitudinal, time-to-event, and joint models due to clinical relevance. Investigate gender, prevOI (indicator for AIDs diagnosis / previous opportunistic infection at study entry), and AZT (AZT intolerance/failure indicator) for inclusion.",
        },
        {
          title: "Answer the two research questions",
          detail:
            "Question 1: For patients diagnosed with HIV, does assignment to didanosine (ddI) compared to zalcitabine (ddC) have an effect separately on (i) CD4 cell count measured longitudinally over time (ii) time until death (iii) simultaneously on both CD4 cell count and time until death? Question 2: Additionally, does the effect of treatment assignment on the two outcomes (separately from analyses (i) and (ii), or simultaneously from analysis (iii)) change when gender, previous opportunistic infections, and AZT intolerance/failure are considered as additional covariates in the analysis?",
        },
        {
          title: "Describe the data and produce a demographics table",
          detail:
            "Examine the dataset provided (aidsdat.dat) and give a brief description of the origin of the data (e.g. type of study the data was collected in, participants) and the clinical background of the data. Produce a demographics table comparing data between treatment groups and overall, appropriately summarising different data types.",
        },
        {
          title: "Make an initial examination of the data",
          detail:
            "Assess whether any further data processing steps might be taken and why (e.g. transformations of skewed data). Report any steps taken in the final write up.",
        },
        {
          title: "Plan and perform the three analyses",
          detail:
            "Plan and perform appropriate data visualisation and methodological analysis for: (i) separate (standalone) analysis of the longitudinal outcome (CD4); (ii) separate (standalone) analysis of the time-to-event outcome (death, time); (iii) joint analysis of the longitudinal and time-to-event outcomes, using the longitudinal and time-to-event models identified in (i) and (ii) to inform the specification of the sub-models inside the joint model.",
        },
        {
          title: "Describe and justify modelling decisions",
          detail:
            "For each of the three sets of analyses: describe different model structures investigated in the methods section (e.g. different association structures, random effects specifications) and reasons for choice; describe the process of selection of appropriate association structures, e.g. through trajectory plots or AIC comparison; describe procedures used to select covariates for each of the three models and to compare model fits (e.g. stepwise procedure); describe procedures to compare different models, e.g. comparison of log-likelihoods or AIC values; state any differences between planned and performed analyses.",
        },
        {
          title: "Write up results for a clinical audience",
          detail:
            "Write up the results of the (i) longitudinal, (ii) time-to-event and (iii) joint modelling analyses, interpreting results appropriately for a clinical audience, and detailing/discussing differences, benefits and drawbacks of different approaches. Structure the write up as the methods and results sections of a journal article (an introduction, discussion, and abstract are not required). References detailing supporting methods and software used are essential.",
        },
        {
          title: "Cite software and include R code appendix",
          detail:
            "Assume all analyses are conducted in R, with statement of details of packages used including version numbers and references for R and each key package. Full R code should be submitted as an appendix to the write up after the references; R code does not count towards the word count. References should be listed after the results section under a heading of \"References\" and also do not count towards the word count.",
        },
        {
          title: "Present tables and figures within the limits",
          detail:
            "Present relevant tables and graphics where relevant in the write up, appearing in the main text (not grouped at the end). There is a hard limit of 5 tables and 5 figures — a limit, not a target. Panelling multiple graphs within a single figure is acceptable if readable. Include figures/tables that reinforce the key messages of the research, and ensure all tables and graphs have a caption and are referred to by number in the main text.",
        },
      ],
      topBandGuidance:
        "Per the rubric's A* (80-100%) descriptors: appropriate methods chosen for all three (longitudinal, time-to-event, joint) analyses, very clearly described and well justified with no errors, such that a future researcher could replicate the analysis exactly; appropriate analysis methods applied without errors for all three analyses with full results presented in an organised manner (estimates with confidence intervals); very detailed and thorough description, interpretation and implications for all three analyses, including comparisons between the standalone and joint modelling results for both longitudinal and time-to-event outcomes; tables/graphs directly tailored to the research question, adhering to the 5-table/5-figure maximum; a very detailed description of attempts to assess model assumptions or validate models; analysis and results very well communicated with clear ordering of background/methods/results/discussion, full interpretation linked back to the clinical area, and references cited throughout with a full reference list; R code submitted as an appendix, organised logically, clear to follow, with informative comments throughout including R/library version details, and all code needed to complete the analysis fully provided.",
      goodWorkLooksLike: [
        "Appropriate, well-justified methods chosen and clearly described for each of the (i) longitudinal, (ii) time-to-event and (iii) joint modelling analyses, detailed enough for exact replication",
        "Methods applied without errors, with full results presented in an organised manner (e.g. tables/text with estimates and confidence intervals)",
        "Thorough interpretation of findings and clinical implications for each analysis, including explicit comparisons between the standalone and joint modelling results",
        "Tables and graphs (demographics table, results tables, Kaplan-Meier curves, longitudinal trajectory plots, joint plots) directly tailored to the research question, staying within the 5-table/5-figure limit, with legends, titles and captions",
        "Detailed, correct discussion of model assumption checking and model validation for each analysis",
        "Results communicated clearly for a clinical audience: ordered background/methods/results/discussion, statistical results linked back to clinical meaning, full and consistently cited references",
        "R code submitted as an appendix, logically organised, with informative comments throughout (including R/library versions) and all code needed to complete the analysis",
      ],
      genAiTier:
        "Tier 3: Structural scaffold (Exploratory / Critical use). GenAI use is broadly allowed and encouraged for specific stages/tasks (e.g. debugging code), but must not be the primary producer of the code or the write-up; code/debugging suggestions from GenAI should be adapted, not pasted verbatim. Students must submit a cover sheet declaring GenAI use with example prompts, and note in R code comments where GenAI assisted.",
      rubric: {
        status: "available",
        tables: [
          {
            criteria: [
              {
                name: "Correctly identify and justify an appropriate method for each of the (i) longitudinal (ii) time-to-event and (iii) joint analyses",
                weight: "20%",
                bands: [
                  {
                    band: "A* Distinction",
                    range: "80-100%",
                    text: "Appropriate methods have been chosen for each of the (i) longitudinal (ii) time-to-event and (iii) joint modelling analyses. These methods are very clearly described throughout and well justified with no errors. Given the supplied information, a future researcher could replicate the analysis exactly.",
                  },
                  {
                    band: "A Distinction",
                    range: "70-79%",
                    text: "Appropriate methods have been chosen for each of the (i) longitudinal, (ii) time-to-event, and (iii) joint modelling analyses. Description of methods and justification of choices is detailed throughout and contains no major errors. Given the supplied information, a future researcher could replicate the analysis almost exactly.",
                  },
                  {
                    band: "B Merit",
                    range: "60-69%",
                    text: "Appropriate methods have been chosen for at least some of the (i) longitudinal, (ii) time-to-event, and (iii) joint modelling analyses. Some details of methods chosen have been reported across the three analyses, but details are not complete. Some justification of method choices across the three analyses have been given. The description and justifications contain only minor errors. Given the supplied information, a future researcher could replicate the analysis similarly, but not exactly.",
                  },
                  {
                    band: "C Pass",
                    range: "50-59%",
                    text: "Some appropriate methods have been chosen for at least some of the (i) longitudinal, (ii) time-to-event, and (iii) joint modelling analyses. There has been some attempt to describe the methods and justify modeling choices. Given the supplied information, a future researcher would struggle to replicate the analysis in a similar way.",
                  },
                  {
                    band: "D Fail",
                    range: "40-49%",
                    text: "There has been minimal attempt to justify model choices or describe the chosen methods, and largely incorrect methods chosen for the (i) longitudinal, (ii) time-to-event, and (iii) joint modelling analyses. Given the supplied information, a future researcher would not be able to replicate the analysis.",
                  },
                  {
                    band: "F Fail",
                    range: "0-39%",
                    text: "There is little attempt to explain choice of methods for the (i) longitudinal, (ii) time-to-event, and (iii) joint modelling analyses, and the methods selected are incorrect. No attempt at justifying model choices. A future researcher could not replicate the analysis based on the supplied information.",
                  },
                ],
              },
              {
                name: "Correctly apply selected methods for each of the (i) longitudinal (ii) time-to-event and (iii) joint modelling analyses",
                weight: "20%",
                bands: [
                  {
                    band: "A* Distinction",
                    range: "80-100%",
                    text: "Appropriate analysis methods have been applied without errors for each of the (i) longitudinal (ii) time-to-event, and (iii) joint modelling analyses. Full results have been presented in an organised manner (e.g. tables or text, with estimates accompanied by confidence intervals etc.)",
                  },
                  {
                    band: "A Distinction",
                    range: "70-79%",
                    text: "Appropriate analysis methods have been applied with minimal errors for each of the (i) longitudinal (ii) time-to-event, and (iii) joint modelling analyses. Results have been presented in an organised manner (e.g. tables or text, with estimates accompanied by confidence intervals etc.)",
                  },
                  {
                    band: "B Merit",
                    range: "60-69%",
                    text: "Appropriate analysis methods have been applied with minimal errors for each of the (i) longitudinal (ii) time-to-event, and (iii) joint modelling analyses. Most results have been presented in an organised manner (e.g. tables or text, with estimates accompanied by confidence intervals etc.)",
                  },
                  {
                    band: "C Pass",
                    range: "50-59%",
                    text: "An attempt has been made to apply appropriate analysis methods for each of the (i) longitudinal (ii) time-to-event, and (iii) joint modelling analyses. There were some issues with the analysis that were not addressed. Some results are presented in a disorganised manner in the writeup (e.g. some confidence intervals missing, not all estimates reported)",
                  },
                  {
                    band: "D Fail",
                    range: "40-49%",
                    text: "An attempt has been made to apply appropriate analysis methods for each of the (i) longitudinal (ii) time-to-event, and (iii) joint modelling analyses, however there are significant issues with the analysis. Limited results are presented in a disorganised manner in the writeup (e.g. some confidence intervals missing, only some estimates reported)",
                  },
                  {
                    band: "F Fail",
                    range: "0-39%",
                    text: "Analysis methods or each of the (i) longitudinal (ii) time-to-event, and (iii) joint modelling analyses have not been correctly applied. Few results are presented, and are incomplete (e.g. missing confidence intervals, missing effect estimates).",
                  },
                ],
              },
              {
                name: "Appropriately interpret the findings of each model and describe the clinical relevance",
                weight: "20%",
                bands: [
                  {
                    band: "A* Distinction",
                    range: "80-100%",
                    text: "Very detailed and thorough description of results, their interpretation and implications for each of the (i) longitudinal (ii) time-to-event, and (iii) joint modelling analyses. A comparison between the standalone longitudinal and the joint modelling longitudinal results has been made. A comparison between the standalone time-to-event and the joint modelling time-to-event results has been made.",
                  },
                  {
                    band: "A Distinction",
                    range: "70-79%",
                    text: "Appropriate attempt to interpret the results and describe their implications, with minimal errors in interpretation. This has been done for each of the (i) longitudinal (ii) time-to-event, and (iii) joint modelling analyses. A comparison between the standalone longitudinal and the joint modelling longitudinal results has been made. A comparison between the standalone time-to-event and the joint modelling time-to-event results has been made. The comparison between standalone and joint analyses may be missing some minor details.",
                  },
                  {
                    band: "B Merit",
                    range: "60-69%",
                    text: "An attempt has been made to interpret the results and describe their implications. There are only minor errors in interpretations. This has been done for each of the (i) longitudinal (ii) time-to-event, and (iii) joint modelling analyses. A comparison between the standalone longitudinal and the joint modelling longitudinal results has been attempted. A comparison between the standalone time-to-event and the joint modelling time-to-event results has been attempted. The comparison between standalone and joint analyses may not be extensive, or may be missing major details.",
                  },
                  {
                    band: "C Pass",
                    range: "50-59%",
                    text: "An attempt has been made to interpret the results and describe their implications. However there are some errors in interpretations, or interpretations may be missing for parts of any or all of the (i) longitudinal (ii) time-to-event, and (iii) joint modelling analyses. Little comparison between standalone and joint analyses have been attempted.",
                  },
                  {
                    band: "D Fail",
                    range: "40-49%",
                    text: "Minimal effort to describe the interpretation of the results or the real world implications. No comparison between standalone and joint analyses have been attempted",
                  },
                  {
                    band: "F Fail",
                    range: "0-39%",
                    text: "Results have not been described and the clinical interpretation has not been given.",
                  },
                ],
                sourceNote:
                  "Rubric criterion header in the source workbook reads \"clinical relevances\" [sic]; the App's field name above corrects only the grammar of the label field, the band text is reproduced verbatim.",
              },
              {
                name: "Data Visualisation",
                weight: "10%",
                bands: [
                  {
                    band: "A* Distinction",
                    range: "80-100%",
                    text: "As for A - Distinction (70-79%), but additionally tables and graphs have been directly tailored to the research question (e.g. showing evidence aiding comparison of standalone longitudinal and time-to-event analyses against joint modelling analysis. The maximum number of tables and plots has been adhered to (5 tables, 5 plots).",
                  },
                  {
                    band: "A Distinction",
                    range: "70-79%",
                    text: "Good visualisations / summarise [sic] of both the data and the analyses have been provided (there is a demographics table, results table(s) summarising (i) the standalone longitudinal analysis, (ii) the standalone time-to-event analysis, and (iii) the joint modelling analysis, and at least one suitable graph for each of the (i) longitudinal, (ii) time-to-event and (iii) joint modelling components). Plots and tables are easy to read, and contain all necessary details such as legends, titles, captions, details of data summaries). Thought has been given as to which visualisations to include in the main text and whether to include some in appendices. Tables and graphs have been referred to and discussed appropriately in the main text, and are used to back up the message of the analysis. The maximum number of tables and plots has been adhered to (5 tables, 5 plots).",
                  },
                  {
                    band: "B Merit",
                    range: "60-69%",
                    text: "Visualisations of both data and analyses have been provided (at least some of demographics tables, results tables, Kaplan Meier Curves, Longitudinal trajectory plots, joint plots etc.). Plots and tables are relatively easy to read, and contain necessary details such as legends, titles, captions, details of data summaries). Some improvement is possible in the presentation of data e.g. thought into which graphs / tables to include in the main text, or how to improve how readable they are. Tables and graphs have been briefly referred to in the main text. The maximum number of tables and plots (5 tables, 5 plots) may not have been adhered to.",
                  },
                  {
                    band: "C Pass",
                    range: "50-59%",
                    text: "Some visualisations of data / analyses are provided e.g. possibly incomplete tables or graphs representing the data or analysis results (demographics tables, results tables, Kaplan Meier Curves, Longitudinal trajectory plots, joint plots etc.). Plots / tables might be difficult to read and are missing some but not all key information (e.g. legends, titles, captions, details of types of data summaries). The maximum number of tables and plots (5 tables, 5 plots) may not have been adhered to.",
                  },
                  {
                    band: "D Fail",
                    range: "40-49%",
                    text: "Limited visualisations of data / analyses e.g. possibly incomplete tables or graphs representing the data or analysis results (demographics tables, results tables, Kaplan Meier Curves, Longitudinal trajectory plots, joint plots etc.). Plots / tables might not be appropriate, may be difficult to read, or might be missing key information (e.g. legends, titles, captions, details of types of data summaries). The maximum number of tables and plots (5 tables, 5 plots) may not have been adhered to.",
                  },
                  {
                    band: "F Fail",
                    range: "0-39%",
                    text: "No visualisations of data or analysis (demographics tables, results tables, Kaplan Meier Curves, Longitudinal trajectory plots, joint plots etc.) have been provided.",
                  },
                ],
                sourceNote:
                  "A band contains the verbatim typo \"summarise\" for \"summaries\" and an unclosed parenthesis after \"joint modelling analysis\"; reproduced as-is.",
              },
              {
                name: "Model checking and variable selection",
                weight: "10%",
                bands: [
                  {
                    band: "A* Distinction",
                    range: "80-100%",
                    text: "A very detailed description of attempts to assess model assumption or validate models appropriately. As for distinction but a more complete description.",
                  },
                  {
                    band: "A Distinction",
                    range: "70-79%",
                    text: "There is detailed discussion of modelling assumptions or validation checks. Discussion is correct and not missing any major points.",
                  },
                  {
                    band: "B Merit",
                    range: "60-69%",
                    text: "There is discussion of model assumption checking or model validation where appropriate. Discussion is largely correct and accurate.",
                  },
                  {
                    band: "C Pass",
                    range: "50-59%",
                    text: "There is some limited discussion of model checking or validation. Some limited attempt has been made to assess the performance of models.",
                  },
                  {
                    band: "D Fail",
                    range: "40-49%",
                    text: "Minimal model checking or validation have been presented",
                  },
                  {
                    band: "F Fail",
                    range: "0-39%",
                    text: "No model checking or validation has been presented",
                  },
                ],
              },
              {
                name: "Communication and presentation of analysis and results to a clinical audience",
                weight: "10%",
                bands: [
                  {
                    band: "A* Distinction",
                    range: "80-100%",
                    text: "Analysis and results are very well communicated - e.g. results expected to be present in the write up are fully reported, there is clear order to the presentation of the background, methods, the results and this disucssion [sic], which is easy to follow through the write up, the results presented in tables have been fully discussed and interpreted in the main text. Interpretation has been made, with statistical results related back to the clinical area (e.g. as age increases, risk of event increases). Supporting references are cited throughout and a full reference list has been supplied. There is little improvement possible how the results could be communicated to a clinical audience",
                  },
                  {
                    band: "A Distinction",
                    range: "70-79%",
                    text: "Analysis and results are well communicated -e.g. results expected to be present in the write up are fully reported, there is clear order to the presentation of the background, methods, the results and this disucssion [sic], which is easy to follow through the write up, the results presented in tables have been fully discussed and interpreted in the main text. Interpretation has generally been made, with statistical results related back to the clinical area (e.g. as age increases, risk of event increases). Supporting references are cited throughout and a full reference list has been supplied.",
                  },
                  {
                    band: "B Merit",
                    range: "60-69%",
                    text: "Analysis and results are adequately communicated - e.g. results expected to be present in the write up are generally reported, there is some order to the presentation of the results, there is some attempt to organise the write up content into sections similar to a journal article, there is some linkage between results in tables and in the main text. Interpretation has been made, with some attempt to relate the statistical results to a clinical intepretation [sic]. Supporting references are largely cited throughout and a reference list has been supplied.",
                  },
                  {
                    band: "C Pass",
                    range: "50-59%",
                    text: "Analysis and results are poorly communicated - e.g. results expected to be present in the write up are incomplete, results are presented in a confusing or disorganised way, there minimal is link between results in tables and in the main text, the write up is not organised in a clear way similar to a journal article. Interpretation has been made, but is missing examples to allow clinical audiences to relate the results back to the clinical background of the data. Some effort has been made to provide supporting references and a reference list has been supplied.",
                  },
                  {
                    band: "D Fail",
                    range: "40-49%",
                    text: "Analysis and results are very poorly communicated - e.g. results expected to be present in the write up are incomplete, results are presented in a confusing or disorganised way, there is little link between results in tables and in the main text, there is little interpretation of results, content in the write-up is not organised in a clear way, and the language used is not suitable for a clinical audience. There may be issues with supporting references e.g. missing in text citations, missing reference list etc.",
                  },
                  {
                    band: "F Fail",
                    range: "0-39%",
                    text: "Analysis and results are barely communicated - e.g. results expected to be present in the write up are incomplete or completely missing, results and the generaly [sic] assessment are presented in a confusing or disorganised way, there is little link between results in tables and in the main text, no interpretation of results has been given. There are issues with supporting references e.g. missing in text citations, missing reference list etc.",
                  },
                ],
                sourceNote:
                  "Rubric text contains verbatim typos \"disucssion\", \"intepretation\" and \"generaly\", plus a grammatical slip \"there minimal is link\" in the C band; all reproduced as-is.",
              },
              {
                name: "Clear and readable R code",
                weight: "10%",
                bands: [
                  {
                    band: "A* Distinction",
                    range: "80-100%",
                    text: "R code has been submitted as an appendix to the main write up. It is organised in a logical manner, and it clear and easy for the reader to follow what has been been done. There are informative comments throughout, and the code needed to complete the analysis is fully provided (e.g. listing of libraries used, code to generate tables etc.). Comments contain details of versions of R and libraries used",
                  },
                  {
                    band: "A Distinction",
                    range: "70-79%",
                    text: "R code has been submitted as an appendix to the main write up. It is organised in a logical manner, and it is clear for the reader to follow what has been been done. There are comments throughout, and the code needed to complete the analysis is provided (e.g. listing of libraries used, code to generate tables etc.)",
                  },
                  {
                    band: "B Merit",
                    range: "60-69%",
                    text: "R code has been submitted as an appendix to the main write up. It is organised in a logical manner, and it is relatively easy for the reader to follow what has been been done. There are some comments, and most of the code needed to complete the analysis is provided (e.g. listing of libraries used, code to generate tables etc.)",
                  },
                  {
                    band: "C Pass",
                    range: "50-59%",
                    text: "R code has been submitted as an appendix to the main write up. It is not well organised, and it is difficult to easily follow what has been done. Comments are minimal and/or uninformative. Sections of code might be missing / incomplete (e.g. listing of libraries used, code to generate tables etc.)",
                  },
                  {
                    band: "D Fail",
                    range: "40-49%",
                    text: "Minimal R code has been submitted. It is disorganised, uncommented and incomplete (missing key sections of code)",
                  },
                  {
                    band: "F Fail",
                    range: "0-39%",
                    text: "No R code has been submitted",
                  },
                ],
                sourceNote:
                  "Rubric text contains the repeated verbatim phrase \"what has been been done\" in the A*/A/B bands; reproduced as-is.",
              },
            ],
            academicIntegrity: [
              {
                label: "No concerns",
                text: "There are no academic integrity concerns with this assignment",
              },
              {
                label: "Category 1",
                text: "Poor Academic Practice. The assessed mark is capped at minimum pass grade (50%). Assessors are advised to consult with the Academic Integrity Officer (mesudell@liverpool.ac.uk)",
              },
              {
                label: "Category 2, 3, 4",
                text: "(Plagiarism, Copying, Collusion, Submission of Unacceptable Artificial Intelligence Generated Assessment Tasks, Embellishment or Falsification of Data, Purchased or commissioned work). All suspected Cat 2, 3, 4 cases must be referred to the Academic Integrity Officer (mesudell@liverpool.ac.uk)",
              },
            ],
          },
        ],
      },
      readingRefs: [
        {
          title: "How to Write Your Methods",
          author: "PLOS",
          note: "https://plos.org/resource/how-to-write-your-methods/",
        },
        {
          title: "How to Report Statistics",
          author: "PLOS",
          note: "https://plos.org/resource/how-to-report-statistics/",
        },
        {
          title: "Exemplar scientific writing",
          note: "Available on the general programme Canvas page",
        },
      ],
      gaps: [
        "No explicit page limit or time limit is stated (only a word limit, plus the hard limit of 5 tables and 5 figures).",
        "Weighting of 50% is not stated as a standalone figure in the Assignment 2 rubric itself; it comes from the guide's introductory statement that the two DASC506 assignments are \"each worth 50%\", and the rubric totals to 100 marks.",
        "The guide references a Programme Handbook (\"The usual guidance on preparation, submission and assessment of assignments applies\") which was not supplied, so handbook-level rules (e.g. late penalties, extension process) are not available.",
      ],
    },
  ],
  notes: [
    "Module-level fact stated in the Assignment 2 guide's introduction: \"There are two assignments in DASC506, each worth 50%.\" This is the only explicit statement of relative weighting found across the four source files.",
    "Source documents (verbatim extraction, University of Liverpool Health Data Science programme): 'DASC506 - Assignment 1 Prediction Modelling - student guide 26-27.docx', 'DASC506 - Prediction Modelling - Marking Rubric.xlsx', 'Assignment 2 - Joint Modelling - Student Guide.docx', 'DASC506 Assignment 2 Joint Modelling - Marking Rubric.xlsx'.",
  ],
};
